crypto: xts: Rename free() to xts_free()
GCC 10 doesn't like it when reserved function names are used:
crypto/xts.c:337:13: error: conflicting types for built-in function 'free'; expected 'void(void *)' [-Werror=builtin-declaration-mismatch]
  337 | static void free(struct crypto_instance *inst)
      |             ^~~~
crypto/xts.c:27:1: note: 'free' is declared in header '<stdlib.h>'
   26 | #include <crypto/gf128mul.h>
  +++ |+#include <stdlib.h>
   27 |

Signed-off-by: Sultan Alsawaf <sultan@kerneltoast.com>
Signed-off-by: wulan17 <galihgustip@gmail.com>